# Imports

In [1]:
import pandas as pd
import datetime
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Parte 2 - Cuidando das categóricas

In [2]:
# Definindo uma função para trocar para um tipo de variável que usa menos memória
def reduz_memoria(df):

    # Criando duas listas para armazenar as colunas que selecionaremos
    colunas_int = []
    colunas_float = []

    # Laço para iterar em todas as colunas com dados do tipo "int64" e "float64"
    for coluna, tipo in enumerate(df.dtypes):

        # Selecionando as colunas com dados do tipo "int64"
        if tipo == 'int64':

            # Amazenando os nomes das colunas do tipo "int64"
            colunas_int.append(df.dtypes.index[coluna])

            # Realizando a troca para "int16"
            df[colunas_int] = df[colunas_int].astype(np.int16)
        
        # Selecionando as colunas com dados do tipo "int64"
        elif tipo == 'float64':

            # Amazenando os nomes das colunas do tipo "float64"
            colunas_float.append(df.dtypes.index[coluna])

            # Realizando a troca para "float32"
            df[colunas_float] = df[colunas_float].astype('float32')
    
    # Retornando um DataFrame com "int16" e "float32"
    return df

In [3]:
# Carregando a nova base de dados
market = pd.read_csv('market_parte_2.csv')
portifolio1 = pd.read_csv('portfolio1_parte_2.csv')
portifolio2 = pd.read_csv('portfolio2_parte_2.csv')
portifolio3 = pd.read_csv('portfolio3_parte_2.csv')


market = reduz_memoria(market)
portifolio1 = reduz_memoria(portifolio1)

# Transformando a variável 'dt_situacao' para o formato datetime
#portifolio1['dt_situacao'] = portifolio1['dt_situacao'].apply(lambda x: datetime.date(day=int(x.split('-')[2]),
#                                                                                      month=int(x.split('-')[1]),
#                                                                                      year=int(x.split('-')[0])))

index_e_data_portifolio1 = portifolio1[['id', 'dt_situacao']]
index_e_data_market = market[['id', 'dt_situacao']]

portifolio1.drop(index_e_data_portifolio1, axis=1, inplace=True)
market.drop(index_e_data_market, axis=1, inplace=True)

# Selecionando as variáveis categóricas
categoricas_portifolio1 = [coluna for coluna in portifolio1.dtypes[portifolio1.dtypes == 'object'].index if coluna != ['id', 'dt_situacao']]
categoricas_market = [coluna for coluna in market.dtypes[market.dtypes == 'object'].index if coluna != ['id', 'dt_situacao']]

In [4]:
portifolio1.columns.to_list()

['fl_matriz',
 'de_natureza_juridica',
 'sg_uf',
 'natureza_juridica_macro',
 'de_ramo',
 'setor',
 'idade_empresa_anos',
 'idade_emp_cat',
 'fl_me',
 'fl_sa',
 'fl_mei',
 'fl_email',
 'fl_telefone',
 'fl_rm',
 'nm_divisao',
 'nm_segmento',
 'fl_antt',
 'fl_veiculo',
 'fl_optante_simples',
 'vl_total_veiculos_pesados_grupo',
 'vl_total_veiculos_leves_grupo',
 'fl_optante_simei',
 'sg_uf_matriz',
 'de_saude_tributaria',
 'de_saude_rescencia',
 'nu_meses_rescencia',
 'de_nivel_atividade',
 'empsetorcensitariofaixarendapopulacao',
 'nm_meso_regiao',
 'nm_micro_regiao',
 'fl_passivel_iss',
 'qt_socios',
 'qt_socios_pf',
 'qt_socios_pj',
 'idade_media_socios',
 'idade_maxima_socios',
 'idade_minima_socios',
 'qt_socios_st_regular',
 'de_faixa_faturamento_estimado',
 'de_faixa_faturamento_estimado_grupo',
 'vl_faturamento_estimado_aux',
 'vl_faturamento_estimado_grupo_aux',
 'qt_filiais']

In [5]:
['id',
            'fl_matriz',
            'de_natureza_juridica',
            'sg_uf',
            'setor',
            'idade_emp_cat',
            'fl_email',
            'fl_telefone',
            'fl_rm',
            'nm_divisao',
            'nm_segmento',
            'fl_veiculo',
            'fl_optante_simples',
            'fl_optante_simei',
            'de_saude_tributaria',
            'de_nivel_atividade',
            'empsetorcensitariofaixarendapopulacao',
            'nm_meso_regiao',
            'nm_micro_regiao',
            'fl_passivel_iss',
            'qt_socios',
            'idade_media_socios',
            'de_faixa_faturamento_estimado',
            'de_faixa_faturamento_estimado_grupo',
            'qt_filiais']

['id',
 'fl_matriz',
 'de_natureza_juridica',
 'sg_uf',
 'setor',
 'idade_emp_cat',
 'fl_email',
 'fl_telefone',
 'fl_rm',
 'nm_divisao',
 'nm_segmento',
 'fl_veiculo',
 'fl_optante_simples',
 'fl_optante_simei',
 'de_saude_tributaria',
 'de_nivel_atividade',
 'empsetorcensitariofaixarendapopulacao',
 'nm_meso_regiao',
 'nm_micro_regiao',
 'fl_passivel_iss',
 'qt_socios',
 'idade_media_socios',
 'de_faixa_faturamento_estimado',
 'de_faixa_faturamento_estimado_grupo',
 'qt_filiais']

In [6]:
# Selecionando features por maior correlação

In [7]:
# Selecionando as variáveis categóricas COM ordenação
cat_COM_ordem = ['idade_emp_cat', 
                 'de_saude_rescencia', 
                 'de_nivel_atividade', 
                 'de_faixa_faturamento_estimado', 
                 'de_faixa_faturamento_estimado_grupo']

# Criando uma lista que armazena as variáveis categóricas SEM ordenação mais importantes
cat_SEM_ordem = ['de_natureza_juridica',
                 'sg_uf',
                 'de_ramo',
                 'setor', 
                 'nm_divisao', 
                 'nm_segmento',
                 'de_saude_tributaria']

cat_SEM_ordem = []

# Laço que itera em todas as variáveis categóricas
for coluna in categoricas_portifolio1:

    # Separando as variáveis categóricas SEM ordenação
    if coluna not in cat_COM_ordem:

        # Armaxenando as variáveis categóricas SEM ordenação em sua respectiva lista
        cat_SEM_ordem.append(coluna)

In [8]:
pd.set_option('display.max_columns', market.shape[1] + 1)
portifolio1.head(3)
for coluna in cat_SEM_ordem:
    print(len(cat_SEM_ordem))
    print(f'\n\n\n{coluna}===\n\n{market[coluna].unique()}\n\n\n')

14



de_natureza_juridica===

['SOCIEDADE EMPRESARIA LIMITADA' 'EMPRESARIO INDIVIDUAL' 'COOPERATIVA'
 'ASSOCIACAO PRIVADA' 'ENTIDADE SINDICAL' 'CONSORCIO DE SOCIEDADES'
 'SOCIEDADE DE ECONOMIA MISTA' 'CONDOMINIO EDILICIO'
 'ORGAO PUBLICO DO PODER EXECUTIVO FEDERAL' 'MUNICIPIO'
 'ORGAO DE DIRECAO LOCAL DE PARTIDO POLITICO' 'SOCIEDADE ANONIMA ABERTA'
 'EMPRESA INDIVIDUAL DE RESPONSABILIDADE LIMITADA DE NATUREZA EMPRESARIA'
 'CANDIDATO A CARGO POLITICO ELETIVO' 'EMPRESA INDIVIDUAL IMOBILIARIA'
 'ORGAO PUBLICO DO PODER EXECUTIVO ESTADUAL OU DO DISTRITO FEDERAL'
 'SOCIEDADE SIMPLES LIMITADA' 'FUNDACAO PRIVADA'
 'ORGAO PUBLICO DO PODER EXECUTIVO MUNICIPAL' 'SOCIEDADE ANONIMA FECHADA'
 'ORGANIZACAO RELIGIOSA' 'SOCIEDADE UNIPESSOAL DE ADVOCACIA'
 'SOCIEDADE SIMPLES PURA' 'AUTARQUIA FEDERAL'
 'ORGAO PUBLICO DO PODER JUDICIARIO ESTADUAL' 'EMPRESA PUBLICA'
 'SOCIEDADE EMPRESARIA EM NOME COLETIVO' 'AUTARQUIA MUNICIPAL'
 'FUNDO PUBLICO' 'AUTARQUIA ESTADUAL OU DO DISTRITO FEDERAL'
 'FUNDACAO PUBLICA DE DIREITO PUB MUNICIPAL'
 'EMPRESA INDIVIDUAL DE RESPONSABILIDADE LIMITADA DE NATUREZA SIMPLES'
 'ORGAO PUBLICO DO PODER LEGISLATIVO MUNICIPAL'
 'SERVICO NOTARIAL E REGISTRAL CARTORIO' 'ORGANIZACAO SOCIAL OS'
 'CONSORCIO PUBDE DIREITO PUB ASS PUB'
 'ORGAO DE DIRECAO REGIONAL DE PARTIDO POLITICO' 'SERVICO SOCIAL AUTONOMO'
 'SOCIEDADE EM CONTA DE PARTICIPACAO' 'GRUPO DE SOCIEDADES'
 'SOCIEDADE MERCANTIL DE CAPITAL E INDUSTRIA'
 'FUNDACAO PUBLICA DE DIREITO PRIVADO MUNICIPAL'
 'ORGAO PUBLICO AUTONOMO MUNICIPAL'
 'ORGAO PUBLICO DO PODER JUDICIARIO FEDERAL' 'NATUREZA JURIDICA INVALIDA'
 'SOCIEDADE EMPRESARIA EM COMANDITA POR ACOES'
 'FUNDACAO PUBLICA DE DIREITO PUBFEDERAL'
 'ORGAO PUBLICO AUTONOMO ESTADUAL OU DO DISTRITO FEDERAL'
 'ESTABELECIMENTO NO BRASIL DE SOCIEDADE ESTRANGEIRA'
 'FUNDACAO PUB DE DIREITO PUB EST OU DO DF'
 'ORGAO PUBLICO DO PODER LEGISLATIVO ESTADUAL OU DO DISTRITO FEDERAL'
 'ENTIDADE DE MEDIACAO E ARBITRAGEM' 'COMUNIDADE INDIGENA'
 'FUNDACAO PUBLICA DE DIREITO PRIVADO FEFERAL'
 'ESTABELECIMENTO NO BRASIL DE FUNDACAO OU ASSOCIACAO ESTRANGEIRAS'
 'CLUBE FUNDO DE INVESTIMENTO' 'REPRESENTACAO DIPLOMATICA ESTRANGEIRA'
 'SOCIEDADE SIMPLES EM COMANDITA SIMPLES'
 'CONSORCIO PUBLICO DE DIREITO PRIVADO'
 'FRENTE PLEBISCITARIA OU REFERENDARIA'
 'SOCIEDADE EMPRESARIA EM COMANDITA SIMPLES' 'CONSORCIO DE EMPREGADORES'
 'SOCIEDADE SIMPLES EM NOME COLETIVO' 'FUNDO PRIVADO'
 'ESTADO OU DISTRITO FEDERAL' 'ORGAO PUBLICO DO PODER LEGISLATIVO FEDERAL'
 'ORGAO DE DIRECAO NACIONAL DE PARTIDO POLITICO']



14



sg_uf===

['RN' 'PI' 'AM' 'MA' 'RO' 'AC']



14



natureza_juridica_macro===

['ENTIDADES EMPRESARIAIS' 'OUTROS' 'ENTIDADES SEM FINS LUCRATIVOS'
 'ADMINISTRACAO PUBLICA' 'CARGO POLITICO' 'PESSOAS FISICAS'
 'INSTITUICOES EXTRATERRITORIAIS']



14



de_ramo===

['INDUSTRIA DA CONSTRUCAO' 'SERVICOS DE ALOJAMENTO/ALIMENTACAO'
 'TRANSPORTE, ARMAZENAGEM E CORREIO' 'SERVICOS DIVERSOS'
 'SERVICOS PROFISSIONAIS, TECNICOS E CIENTIFICOS' 'QUIMICA-PETROQUIMICA'
 'SERVICOS ADMINISTRATIVOS' 'BENS DE CONSUMO' 'COMERCIO VAREJISTA'
 'INDUSTRIA DIGITAL' 'TEXTEIS' 'COMERCIO POR ATACADO' 'TELECOM'
 'SERVICOS DE SAUDE' 'COMERCIO E REPARACAO DE VEICULOS'
 'CULTURA, ESPORTE E RECREACAO' 'SERVICOS FINANCEIROS'
 'SERVICOS DE EDUCACAO' 'PRODUTOS DE AGROPECUARIA'
 'ADMINISTRACAO PUBLICA, DEFESA E SEGURIDADE SOCIAL' 'PAPEL E CELULOSE'
 'SIDERURGICA-METALURGIA' 'OUTROS'
 'SEGUROS, PLANOS DE PREVIDENCIA E PLANOS DE SAUDE' 'ELETRICIDADE E GAS'
 'INDUSTRIAS EXTRATIVAS' 'ELETROELETRONICOS'
 'SERVICOS DE SANEAMENTO BASICO' 'ATIVIDADES IMOBILIARIAS'
 'SERVICOS SOCIAIS' 'INDUSTRIA AUTOMOTIVA' 'ORGANISMOS INTERNACIONAIS'
 'FARMACEUTICA']



14



setor===

['CONSTRUÇÃO CIVIL' 'SERVIÇO' 'INDUSTRIA' 'COMERCIO' 'AGROPECUARIA' nan]



14



fl_rm===

['SIM' 'NAO']



14



nm_divisao===

['CONSTRUCAO DE EDIFICIOS' 'ALIMENTACAO' 'TRANSPORTE TERRESTRE'
 'REPARACAO E MANUTENCAO DE EQUIPAMENTOS DE INFORMATICA E COMUNICACAO E DE OBJETOS PESSOAIS E DOMESTICOS'
 'SERVICOS DE ARQUITETURA E ENGENHARIA TESTES E ANALISES TECNICAS'
 'FABRICACAO DE PRODUTOS DE MINERAIS NAO METALICOS'
 'AGENCIAS DE VIAGENS OPERADORES TURISTICOS E SERVICOS DE RESERVAS'
 'FABRICACAO DE PRODUTOS DIVERSOS' 'COMERCIO VAREJISTA'
 'SERVICOS DE ESCRITORIO DE APOIO ADMINISTRATIVO E OUTROS SERVICOS PRESTADOS PRINCIPALMENTE AS EMPRESAS'
 'ALOJAMENTO' 'SERVICOS ESPECIALIZADOS PARA CONSTRUCAO'
 'ATIVIDADES DE ORGANIZACOES ASSOCIATIVAS'
 'MANUTENCAO REPARACAO E INSTALACAO DE MAQUINAS E EQUIPAMENTOS'
 'ATIVIDADES DE PRESTACAO DE SERVICOS DE INFORMACAO'
 'OUTRAS ATIVIDADES DE SERVICOS PESSOAIS' 'FABRICACAO DE PRODUTOS TEXTEIS'
 'COMERCIO POR ATACADO EXCETO VEICULOS AUTOMOTORES E MOTOCICLETAS'
 'TELECOMUNICACOES' 'ATIVIDADES DE ATENCAO A SAUDE HUMANA'
 'COMERCIO E REPARACAO DE VEICULOS AUTOMOTORES E MOTOCICLETAS'
 'ATIVIDADES ESPORTIVAS E DE RECREACAO E LAZER'
 'SERVICOS PARA EDIFICIOS E ATIVIDADES PAISAGISTICAS'
 'ALUGUEIS NAO IMOBILIARIOS E GESTAO DE ATIVOS INTANGIVEIS NAO FINANCEIROS'
 'ARMAZENAMENTO E ATIVIDADES AUXILIARES DOS TRANSPORTES'
 'EDICAO E EDICAO INTEGRADA A IMPRESSAO'
 'ATIVIDADES ARTISTICAS CRIATIVAS E DE ESPETACULOS'
 'CORREIO E OUTRAS ATIVIDADES DE ENTREGA'
 'PREPARACAO DE COUROS E FABRICACAO DE ARTEFATOS DE COURO ARTIGOS PARA VIAGEM E CALCADOS'
 'FABRICACAO DE PRODUTOS ALIMENTICIOS'
 'OUTRAS ATIVIDADES PROFISSIONAIS CIENTIFICAS E TECNICAS'
 'ATIVIDADES JURIDICAS DE CONTABILIDADE E DE AUDITORIA'
 'ATIVIDADES DE SERVICOS FINANCEIROS' 'EDUCACAO' 'PESCA E AQUICULTURA'
 'FABRICACAO DE PRODUTOS DE MADEIRA'
 'ADMINISTRACAO PUBLICA DEFESA E SEGURIDADE SOCIAL'
 'IMPRESSAO E REPRODUCAO DE GRAVACOES'
 'ATIVIDADES DE VIGILANCIA SEGURANCA E INVESTIGACAO'
 'PUBLICIDADE E PESQUISA DE MERCADO'
 'CONFECCAO DE ARTIGOS DO VESTUARIO E ACESSORIOS' 'FABRICACAO DE MOVEIS'
 'AGRICULTURA PECUARIA E SERVICOS RELACIONADOS'
 'FABRICACAO DE PRODUTOS DE METAL EXCETO MAQUINAS E EQUIPAMENTOS'
 'ATIVIDADES DE SEDES DE EMPRESAS E DE CONSULTORIA EM GESTAO EMPRESARIAL'
 'SERVICOS DOMESTICOS' nan 'FABRICACAO DE PRODUTOS QUIMICOS'
 'ATIVIDADES DE ATENCAO A SAUDE HUMANA INTEGRADAS COM ASSISTENCIA SOCIAL PRESTADAS EM RESIDENCIAS COLETIVAS E PARTICULARES'
 'OBRAS DE INFRA ESTRUTURA' 'PRODUCAO FLORESTAL'
 'ATIVIDADES CINEMATOGRAFICAS PRODUCAO DE VIDEOS E DE PROGRAMAS DE TELEVISAO GRAVACAO DE SOM E EDICAO DE MUSICA'
 'ATIVIDADES DE RADIO E DE TELEVISAO'
 'ATIVIDADES LIGADAS AO PATRIMONIO CULTURAL E AMBIENTAL'
 'ATIVIDADES AUXILIARES DOS SERVICOS FINANCEIROS SEGUROS PREVIDENCIA COMPLEMENTAR E PLANOS DE SAUDE'
 'ELETRICIDADE GAS E OUTRAS UTILIDADES' 'EXTRACAO DE MINERAIS METALICOS'
 'TRANSPORTE AQUAVIARIO' 'FABRICACAO DE BEBIDAS'
 'FABRICACAO DE MAQUINAS APARELHOS E MATERIAIS ELETRICOS'
 'EXTRACAO DE MINERAIS NAO METALICOS'
 'ATIVIDADES DOS SERVICOS DE TECNOLOGIA DA INFORMACAO'
 'CAPTACAO TRATAMENTO E DISTRIBUICAO DE AGUA' 'ATIVIDADES VETERINARIAS'
 'ATIVIDADES IMOBILIARIAS' 'SERVICOS DE ASSISTENCIA SOCIAL SEM ALOJAMENTO'
 'COLETA TRATAMENTO E DISPOSICAO DE RESIDUOS RECUPERACAO DE MATERIAIS'
 'ESGOTO E ATIVIDADES RELACIONADAS'
 'FABRICACAO DE PRODUTOS DE BORRACHA E DE MATERIAL PLASTICO'
 'SELECAO AGENCIAMENTO E LOCACAO DE MAO DE OBRA' 'TRANSPORTE AEREO'
 'FABRICACAO DE VEICULOS AUTOMOTORES REBOQUES E CARROCERIAS'
 'FABRICACAO DE CELULOSE PAPEL E PRODUTOS DE PAPEL'
 'SEGUROS RESSEGUROS PREVIDENCIA COMPLEMENTAR E PLANOS DE SAUDE'
 'FABRICACAO DE EQUIPAMENTOS DE INFORMATICA PRODUTOS ELETRONICOS E OPTICOS'
 'METALURGIA' 'FABRICACAO DE MAQUINAS E EQUIPAMENTOS'
 'ATIVIDADES DE EXPLORACAO DE JOGOS DE AZAR E APOSTAS'
 'FABRICACAO DE OUTROS EQUIPAMENTOS DE TRANSPORTE EXCETO VEICULOS AUTOMOTORES'
 'ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUICOES EXTRATERRITORIAIS'
 'FABRICACAO DE COQUE DE PRODUTOS DERIVADOS DO PETROLEO E DE BIOCOMBUSTIVEIS'
 'PESQUISA E DESENVOLVIMENTO CIENTIFICO'
 'ATIVIDADES DE APOIO A EXTRACAO DE MINERAIS'
 'EXTRACAO DE PETROLEO E GAS NATURAL'
 'FABRICACAO DE PRODUTOS FARMOQUIMICOS E FARMACEUTICOS'
 'DESCONTAMINACAO E OUTROS SERVICOS DE GESTAO DE RESIDUOS'
 'EXTRACAO DE CARVAO MINERAL' 'FABRICACAO DE PRODUTOS DO FUMO']



14



nm_segmento===

['CONSTRUCAO' 'ALOJAMENTO E ALIMENTACAO'
 'TRANSPORTE ARMAZENAGEM E CORREIO' 'OUTRAS ATIVIDADES DE SERVICOS'
 'ATIVIDADES PROFISSIONAIS CIENTIFICAS E TECNICAS'
 'INDUSTRIAS DE TRANSFORMACAO'
 'ATIVIDADES ADMINISTRATIVAS E SERVICOS COMPLEMENTARES'
 'COMERCIO; REPARACAO DE VEICULOS AUTOMOTORES E MOTOCICLETAS'
 'INFORMACAO E COMUNICACAO' 'SAUDE HUMANA E SERVICOS SOCIAIS'
 'ARTES CULTURA ESPORTE E RECREACAO'
 'ATIVIDADES FINANCEIRAS DE SEGUROS E SERVICOS RELACIONADOS' 'EDUCACAO'
 'AGRICULTURA PECUARIA PRODUCAO FLORESTAL PESCA E AQUICULTURA'
 'ADMINISTRACAO PUBLICA DEFESA E SEGURIDADE SOCIAL' 'SERVICOS DOMESTICOS'
 nan 'ELETRICIDADE E GAS' 'INDUSTRIAS EXTRATIVAS'
 'AGUA ESGOTO ATIVIDADES DE GESTAO DE RESIDUOS E DESCONTAMINACAO'
 'ATIVIDADES IMOBILIARIAS'
 'ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUICOES EXTRATERRITORIAIS']



14



fl_optante_simples===

[True nan False]



14



fl_optante_simei===

[False nan True]



14



sg_uf_matriz===

['RN' 'PI' 'AM' 'MA' 'RO' 'AC' 'DF' nan 'CE' 'PB' 'SP' 'PR' 'ES' 'PE' 'MG'
 'RJ' 'RS' 'GO' 'SC' 'BA' 'MT' 'MS' 'PA' 'RR' 'TO' 'AP' 'SE' 'AL']



14



de_saude_tributaria===

['VERDE' 'CINZA' 'AMARELO' 'LARANJA' nan 'AZUL' 'VERMELHO']



14



nm_meso_regiao===

['LESTE POTIGUAR' 'CENTRO NORTE PIAUIENSE' 'CENTRO AMAZONENSE'
 'OESTE POTIGUAR' 'NORTE MARANHENSE' nan 'NORTE PIAUIENSE'
 'SUDOESTE PIAUIENSE' 'AGRESTE POTIGUAR' 'CENTRO MARANHENSE'
 'OESTE MARANHENSE' 'VALE DO ACRE' 'CENTRAL POTIGUAR' 'LESTE MARANHENSE'
 'SUDESTE PIAUIENSE' 'SUL MARANHENSE' 'SUL AMAZONENSE' 'VALE DO JURUA'
 'SUDOESTE AMAZONENSE' 'NORTE AMAZONENSE']



14



nm_micro_regiao===

['NATAL' 'TERESINA' 'MANAUS' 'PAU DOS FERROS'
 'AGLOMERACAO URBANA DE SAO LUIS' 'PARINTINS' 'MOSSORO' 'UMARIZAL' nan
 'COARI' 'LITORAL SUL' 'BAIXO PARNAIBA PIAUIENSE' 'SAO RAIMUNDO NONATO'
 'AGRESTE POTIGUAR' 'MEDIO MEARIM' 'GURUPI' 'BRASILEIA' 'SERIDO OCIDENTAL'
 'ALTO MEDIO GURGUEIA' 'CHAPADAS DO EXTREMO SUL PIAUIENSE' 'CHAPADINHA'
 'PRESIDENTE DUTRA' 'ALTO MEARIM E GRAJAU' 'FLORIANO' 'CAXIAS'
 'IMPERATRIZ' 'CHAPADAS DO ALTO ITAPECURU' 'CAMPO MAIOR' 'CODO'
 'BAIXADA MARANHENSE' 'ITACOATIARA' 'RIO BRANCO' 'PINDARE' 'PIO IX'
 'SERIDO ORIENTAL' 'LENCOIS MARANHENSES' 'LITORAL NORDESTE' 'VALE DO ACU'
 'LITORAL PIAUIENSE' 'BORBOREMA POTIGUAR' 'CHAPADAS DAS MANGABEIRAS'
 'RIO PRETO DA EVA' 'COELHO NETO' 'BOCA DO ACRE' 'BERTOLINIA' 'PICOS'
 'CRUZEIRO DO SUL' 'MACAU' 'SERRA DE SANTANA' 'SERRA DE SAO MIGUEL' 'TEFE'
 'PORTO FRANCO' 'ALTO MEDIO CANINDE' 'LITORAL OCIDENTAL MARANHENSE'
 'VALENCA DO PIAUI' 'GERAIS DE BALSAS' 'MADEIRA' 'ALTO PARNAIBA PIAUIENSE'
 'CHAPADA DO APODI' 'TARAUACA' 'ALTO SOLIMOES' 'MACAIBA' 'RIO NEGRO'
 'BAIXO PARNAIBA MARANHENSE' 'PURUS' 'JURUA' 'BAIXA VERDE'
 'MEDIO PARNAIBA PIAUIENSE' 'ITAPECURU MIRIM' 'SENA MADUREIRA' 'ROSARIO'
 'ANGICOS' 'MEDIO OESTE' 'JAPURA']

In [9]:
# Criando alguns dicionários para transformar as variáveis categóricas COM 
#   ordenação em variáveis numéricas

dicionarios = {'idade_emp_cat': {'<= 1': 0,
                                 '1 a 5': 1,
                                 '5 a 10': 2, 
                                 '10 a 15': 3, 
                                 '15 a 20': 4, 
                                 '> 20': 5
                                 }, 
               
               'de_saude_rescencia': {'SEM INFORMACAO': 0, 
                                      'ATE 3 MESES': 1, 
                                      'ATE 6 MESES': 2, 
                                      'ATE 1 ANO': 3, 
                                      'ACIMA DE 1 ANO': 4
                                      }, 
               
               'de_nivel_atividade': {'MUITO BAIXA': 0, 
                                      'BAIXA': 1, 
                                      'MEDIA': 2, 
                                      'ALTA': 3
                                      }, 
               
               'de_faixa_faturamento_estimado': {'SEM INFORMACAO': 0, 
                                                 'ATE R$ 81.000,00': 1, 
                                                 'DE R$ 81.000,01 A R$ 360.000,00': 2, 
                                                 'DE R$ 360.000,01 A R$ 1.500.000,00': 3, 
                                                 'DE R$ 1.500.000,01 A R$ 4.800.000,00': 4, 
                                                 'DE R$ 4.800.000,01 A R$ 10.000.000,00': 5, 
                                                 'DE R$ 10.000.000,01 A R$ 30.000.000,00': 6, 
                                                 'DE R$ 30.000.000,01 A R$ 100.000.000,00': 7, 
                                                 'DE R$ 100.000.000,01 A R$ 300.000.000,00': 8, 
                                                 'DE R$ 300.000.000,01 A R$ 500.000.000,00': 9, 
                                                 'DE R$ 500.000.000,01 A 1 BILHAO DE REAIS': 10, 
                                                 'ACIMA DE 1 BILHAO DE REAIS': 11
                                                 }, 
               
               'de_faixa_faturamento_estimado_grupo': {'ATE R$ 81.000,00': 1, 
                                                       'DE R$ 81.000,01 A R$ 360.000,00': 2, 
                                                       'DE R$ 360.000,01 A R$ 1.500.000,00': 3, 
                                                       'DE R$ 1.500.000,01 A R$ 4.800.000,00': 4, 
                                                       'DE R$ 4.800.000,01 A R$ 10.000.000,00': 5, 
                                                       'DE R$ 10.000.000,01 A R$ 30.000.000,00': 6, 
                                                       'DE R$ 30.000.000,01 A R$ 100.000.000,00': 7, 
                                                       'DE R$ 300.000.000,01 A R$ 500.000.000,00': 8, 
                                                       'DE R$ 100.000.000,01 A R$ 300.000.000,00': 9, 
                                                       'DE R$ 500.000.000,01 A 1 BILHAO DE REAIS': 10, 
                                                       'ACIMA DE 1 BILHAO DE REAIS': 11
                                                       }
}

In [10]:
portifolio1.de_nivel_atividade

0      BAIXA
1      MEDIA
2      MEDIA
3       ALTA
4       ALTA
       ...
550    MEDIA
551    BAIXA
552    MEDIA
553    BAIXA
554    MEDIA
Name: de_nivel_atividade, Length: 555, dtype: object

In [11]:
# Tratando as categóricas ordinais
for coluna in cat_COM_ordem:
    portifolio1[coluna] = portifolio1[coluna].map(dicionarios[coluna])
print(f'portifolio1 ==> {portifolio1.shape}')

# Tratando as categóricas ordinais
for coluna in cat_COM_ordem:
    market[coluna] = market[coluna].map(dicionarios[coluna])
print(f'market ==> {market.shape}')

portifolio1 ==> (555, 43)
market ==> (462298, 47)

In [12]:
portifolio1.de_nivel_atividade

0      1.0
1      2.0
2      2.0
3      3.0
4      3.0
      ...
550    2.0
551    1.0
552    2.0
553    1.0
554    2.0
Name: de_nivel_atividade, Length: 555, dtype: float64

In [13]:
# Instanciando uma classe LabelEncoder
LE = LabelEncoder()

# Aplicando o LabelEncoder nas colunas categóricas sem ordenação
portifolio1[cat_SEM_ordem] = portifolio1[cat_SEM_ordem].apply(lambda x: LE.fit_transform(x.astype(str)))
market[cat_SEM_ordem] = market[cat_SEM_ordem].apply(lambda x: LE.fit_transform(x.astype(str)))
market.head(10)

,fl_matriz,de_natureza_juridica,sg_uf,natureza_juridica_macro,de_ramo,setor,idade_empresa_anos,idade_emp_cat,fl_me,fl_sa,fl_mei,fl_ltda,fl_st_especial,fl_email,fl_telefone,fl_rm,nm_divisao,nm_segmento,fl_spa,fl_antt,fl_veiculo,fl_optante_simples,vl_total_veiculos_pesados_grupo,vl_total_veiculos_leves_grupo,fl_optante_simei,sg_uf_matriz,de_saude_tributaria,de_saude_rescencia,nu_meses_rescencia,de_nivel_atividade,fl_simples_irregular,empsetorcensitariofaixarendapopulacao,nm_meso_regiao,nm_micro_regiao,fl_passivel_iss,qt_socios,qt_socios_pf,qt_socios_pj,idade_media_socios,idade_maxima_socios,idade_minima_socios,qt_socios_st_regular,de_faixa_faturamento_estimado,de_faixa_faturamento_estimado_grupo,vl_faturamento_estimado_aux,vl_faturamento_estimado_grupo_aux,qt_filiais
0,1,60,4,2,11,2,14.457534,3,0,0,0,0,0,1,1,1,32,10,False,False,False,1,0.0,0.0,0,19,4,4.0,23.0,3.0,False,NaN,6,48,True,2.0,2.0,0.0,44.0,47.0,41.0,2.0,4.0,4.0,3132172.75,3132172.75,0
1,1,17,3,5,21,4,1.463014,1,0,0,1,0,0,1,1,1,3,3,False,False,False,2,0.0,0.0,2,16,2,3.0,9.0,1.0,False,468.929993,4,69,True,1.0,1.0,0.0,27.0,27.0,27.0,1.0,2.0,2.0,210000.00,210000.00,0
2,1,17,1,5,32,4,7.093151,2,0,0,1,0,0,0,1,1,86,20,False,False,False,1,0.0,0.0,1,2,0,4.0,26.0,2.0,False,713.500000,2,43,True,1.0,1.0,0.0,32.0,32.0,32.0,NaN,1.0,1.0,50000.00,50000.00,0
3,1,17,1,5,25,4,6.512329,2,0,0,0,0,0,1,1,1,74,17,False,False,False,1,0.0,0.0,0,2,0,4.0,26.0,2.0,False,475.730011,2,43,True,1.0,1.0,0.0,36.0,36.0,36.0,1.0,2.0,2.0,210000.00,210000.00,0
4,1,17,4,5,27,4,3.200000,1,0,0,0,0,0,1,1,1,77,8,False,False,False,1,0.0,0.0,0,19,4,4.0,27.0,3.0,False,2874.040039,6,48,True,1.0,1.0,0.0,NaN,NaN,NaN,NaN,2.0,2.0,210000.00,210000.00,0
5,1,60,4,2,18,3,38.079453,5,0,0,0,0,0,0,0,0,55,13,False,False,False,0,0.0,0.0,0,19,3,4.0,48.0,3.0,False,NaN,11,50,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,210000.00,210000.00,0
6,1,17,2,5,32,4,7.276712,2,0,0,1,0,0,1,0,1,86,20,False,False,False,1,0.0,0.0,1,9,0,4.0,23.0,2.0,False,NaN,8,0,True,1.0,1.0,0.0,63.0,63.0,63.0,1.0,1.0,1.0,50000.00,50000.00,0
7,1,17,4,5,20,4,0.052055,0,0,0,1,0,0,1,1,1,1,5,False,False,False,2,0.0,0.0,2,19,6,NaN,NaN,3.0,False,NaN,6,48,True,1.0,1.0,0.0,40.0,40.0,40.0,1.0,NaN,NaN,NaN,NaN,0
8,1,12,1,2,2,3,12.263014,3,0,0,0,0,0,0,1,0,56,13,False,False,False,1,0.0,0.0,0,2,1,4.0,24.0,3.0,False,247.880005,2,49,True,2.0,2.0,0.0,36.0,36.0,36.0,1.0,2.0,2.0,210000.00,210000.00,0
9,0,17,4,5,5,1,17.942465,4,0,0,0,0,0,0,0,0,30,9,False,False,False,0,0.0,0.0,0,19,5,4.0,54.0,2.0,False,1042.849976,11,47,False,1.0,1.0,0.0,52.0,52.0,52.0,NaN,2.0,3.0,210000.00,840000.00,3

In [14]:
print(f'portifolio1 ==> {portifolio1.shape}')
print(f'market ==> {market.shape}')

portifolio1 ==> (555, 43)
market ==> (462298, 47)

In [15]:
#sem_cat_market = pd.DataFrame()
#sem_cat_portifolio1 = pd.DataFrame()

#for coluna in cat_SEM_ordem:
#    sem_cat_market = pd.concat([sem_cat_market, pd.get_dummies(market[coluna], dummy_na=True)]
#    sem_cat_portifolio1 = pd.concat([sem_cat_portifolio1, pd.get_dummies(portifolio1[coluna], dummy_na=True)]

In [16]:
#portifolio1 = portifolio1.join(sem_cat_portifolio1, how='outer')
#portifolio1.drop(cat_SEM_ordem, axis=1, inplace=True)
#print(f'portifolio1 ==> {portifolio1.shape}')

#market = market.join(sem_cat_market, how='outer')
#market.drop(cat_SEM_ordem, axis=1, inplace=True)
#print(f'market ==> {market.shape}')

In [17]:
portifolio1.isna().sum()[portifolio1.isna().sum() > 0]

de_saude_rescencia                        11
nu_meses_rescencia                        47
de_nivel_atividade                         4
empsetorcensitariofaixarendapopulacao    150
qt_socios                                147
qt_socios_pf                             147
qt_socios_pj                             147
idade_media_socios                       193
idade_maxima_socios                      193
idade_minima_socios                      193
qt_socios_st_regular                     195
de_faixa_faturamento_estimado             25
de_faixa_faturamento_estimado_grupo       25
vl_faturamento_estimado_aux               25
vl_faturamento_estimado_grupo_aux         25
dtype: int64

In [18]:
market.isna().sum()[market.isna().sum() > 0]

fl_spa                                     1927
fl_antt                                    1927
fl_veiculo                                 1927
vl_total_veiculos_pesados_grupo            1927
vl_total_veiculos_leves_grupo              1927
de_saude_rescencia                        14851
nu_meses_rescencia                        45276
de_nivel_atividade                        11168
fl_simples_irregular                       1927
empsetorcensitariofaixarendapopulacao    143829
fl_passivel_iss                            1927
qt_socios                                115091
qt_socios_pf                             115091
qt_socios_pj                             115091
idade_media_socios                       151602
idade_maxima_socios                      151602
idade_minima_socios                      151602
qt_socios_st_regular                     154917
de_faixa_faturamento_estimado             27513
de_faixa_faturamento_estimado_grupo       27513
vl_faturamento_estimado_aux               27513
vl_faturamento_estimado_grupo_aux         27513
dtype: int64

In [19]:
for coluna in portifolio1.columns:
    
    media = portifolio1[coluna].mean()
    portifolio1[coluna].fillna(media, inplace=True)
    
for coluna in market.columns:
    
    media = market[coluna].mean()
    market[coluna].fillna(media, inplace=True)

In [20]:
portifolio1.isna().sum()[portifolio1.isna().sum() > 0]

Series([], dtype: int64)

In [21]:
market.isna().sum()[market.isna().sum() > 0]

Series([], dtype: int64)

In [22]:
portifolio1 = pd.concat([index_e_data_portifolio1, portifolio1], axis=1)
market = pd.concat([index_e_data_market, market], axis=1)

In [23]:
portifolio1.iloc[:, :-1].to_csv('portfolio1_parte_3.csv', index=False)
market.iloc[:, :-1].to_csv('market_parte_3.csv', index=False)